# Generated by Django 3.1.7 on 2021-05-04 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('fecha_contenido', models.DateTimeField()),
                ('imagen', models.ImageField(upload_to='static/images/fotospost')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('Nombre_Sección', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Nombre_Responsable', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('Nombre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('Dni', models.CharField(max_length=9)),
                ('Fecha_Nacimiento', models.DateField()),
                ('Fecha_Alta_Usuario', models.DateField(auto_now_add=True)),
                ('Sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=1)),
                ('Vigencia', models.BooleanField(default=True)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miaplicacion.seccion')),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('Codigo', models.CharField(max_length=30)),
                ('Nombre_Actividad', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Fecha_Actividad', models.DateTimeField()),
                ('Numero_Usuarios', models.PositiveSmallIntegerField(default=100)),
                ('Descripcion_Actividad', models.CharField(max_length=550)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miaplicacion.seccion')),
                ('usuarioActividad', models.ManyToManyField(blank=True, null=True, to='miaplicacion.Usuario')),
            ],
        ),
    ]
